services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - common_net
volumes:
  pgdata:

networks:
  common_net:
    external: true