services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - common_net

  zookeeper:
    image: bitnami/zookeeper:3.8.4-debian-12-r11
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_CFG_AUDIT_ENABLESERVER=true
    networks:
      - common_net

  kafka:
    image : bitnami/kafka:latest
    volumes:
      - .db_script/docker-compose_kafka_config.yml:/app/db_script/docker-compose_kafka_config.yml:ro  # ro - только чтение файла
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
        KAFKA_ENABLE_KRAFT: "false"
        KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_CFG_BROKER_ID: "1"
        KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
        KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
        KAFKA_CFG_ALLOW_PLAINTEXT_LISTENER: "yes"
        KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - common_net

volumes:
  pgdata:

networks:
  common_net:
    external: true