volumes:
  pgdata:
  redis-data:
services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    env_file:
      - auth_service/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/app/auth_service
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    depends_on:
      - db
      - backend
    volumes:
      - redis-data:/data/redis-data
    #Запускаем шелл, который сперва сделает chown, а потом уже запустит redis-server
    command: >
      sh -c "chown -R redis:redis /data/redis-data && exec redis-server --appendonly yes --dir /data/redis-data"
    restart: unless-stopped
