services:
  postgres:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - common_net

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image : bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  pgdata:

networks:
  common_net:
    external: true