services:
  backend:
    build:
      context: .
      dockerfile: profile/Dockerfile
    env_file:
      - profile/.env
    depends_on:
      - postgres
    ports:
      - "8001:8000"
networks:
  common_net:
    external: true