services:
  backend:
    container_name: service_profile
    build:
      context: .
      dockerfile: profile/Dockerfile
    env_file:
      - profile/.env
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    networks:
      - common_net
networks:
  common_net:
    external: true