services:
  service_article:
    container_name: article_service
    build:
      context: .
      dockerfile: article_service/Dockerfile
    env_file:
      - article_service/.env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "8003:8003"
    networks:
      - kong-net
networks:
  kong-net: