services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - common_net
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - db_script/.env
    volumes:
      - kfdata:/var/lib/kafka/data
#      - /init-topics.sh:/etc/confluent/docker/init-topics.sh:ro
    networks:
      - common_net
  topic-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint:
      - sh
      - -c
      - |
        cub kafka-ready -b kafka:9092 1 20 &&
        kafka-topics --bootstrap-server kafka:9092 \
          --create \
          --topic profile_registration \
          --partitions 1 \
          --replication-factor 1 \
          --if-not-exists
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
    networks:
      - common_net
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  kfdata:

networks:
  common_net:
    external: true