services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_script:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: full_db
    networks:
      - kong-net
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - db_script/.env
    volumes:
      - kfdata:/var/lib/kafka/data
    networks:
      - kong-net
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
  topic-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint:
      - sh
      - -c
      - |
        cub kafka-ready -b kafka:9092 1 20 &&
        kafka-topics --bootstrap-server kafka:9092 \
          --create \
          --topic profile_registration \
          --partitions 1 \
          --replication-factor 1 \
          --if-not-exists
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
    networks:
      - common_net
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  kfdata:

networks:
  kong-net: