services:
  service_profile:
    container_name: service_profile
    build:
      context: .
      dockerfile: profile_service/Dockerfile
    env_file:
      - profile_service/.env
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - "8002:8002"
    networks:
      - kong-net
networks:
  kong-net: